Repository GOSOPT-SOPKATHON-5/SOPKATHON5-Server, pull requests merged in 2023-05, with the labels that each got.

#1 Setting
  .gitignore
  build.gradle
  src/main/java/com/sopkathon/server/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/sopkathon/server/common/advice/CustomException.java
  src/main/java/com/sopkathon/server/common/exception/ControllerExceptionAdvice.java
  src/main/java/com/sopkathon/server/config/QueryDslConfig.java
  src/main/java/com/sopkathon/server/config/SecurityConfig.java
  src/main/java/com/sopkathon/server/domain/Petition.java
  src/main/java/com/sopkathon/server/domain/PetitionLink.java
  src/main/java/com/sopkathon/server/domain/PetitionMember.java
  src/main/java/com/sopkathon/server/domain/User.java
  src/main/resources/application.yaml
Labels: setting, 현정👕

#2 setting
  src/main/java/com/sopkathon/server/common/advice/ConflictException.java
  src/main/java/com/sopkathon/server/common/advice/CustomException.java
  src/main/java/com/sopkathon/server/common/advice/NotFoundException.java
  src/main/java/com/sopkathon/server/common/dto/ApiResponseDto.java
  src/main/java/com/sopkathon/server/common/exception/ErrorStatus.java
  src/main/java/com/sopkathon/server/common/exception/SuccessStatus.java
Labels: setting, 현정👕

#14 #12 get main
  src/main/java/com/sopkathon/server/controller/AnswerController.java
  src/main/java/com/sopkathon/server/dto/request/DeleteResultRequestDto.java
  src/main/java/com/sopkathon/server/service/AnswerService.java
  src/main/java/com/sopkathon/server/service/MainService.java
Labels: feat, 현정👕

#15 Feat/#10 save question and answer
  src/main/java/com/sopkathon/server/ServerApplication.java
  src/main/java/com/sopkathon/server/common/exception/SuccessStatus.java
  src/main/java/com/sopkathon/server/controller/AnswerController.java
  src/main/java/com/sopkathon/server/controller/ResultController.java
  src/main/java/com/sopkathon/server/domain/Result.java
  src/main/java/com/sopkathon/server/dto/request/ResultDto.java
  src/main/java/com/sopkathon/server/dto/request/SaveResultsDto.java
  src/main/java/com/sopkathon/server/dto/request/UpdateUserPointDto.java
  src/main/java/com/sopkathon/server/dto/response/AnswerDetailResponseDto.java
  src/main/java/com/sopkathon/server/dto/response/AnswerResponseDto.java
  src/main/java/com/sopkathon/server/dto/response/UserResponseDto.java
  src/main/java/com/sopkathon/server/repository/AnswerRepository.java
  src/main/java/com/sopkathon/server/repository/QuestionRepository.java
  src/main/java/com/sopkathon/server/repository/ResultRepository.java
  src/main/java/com/sopkathon/server/service/AnswerService.java
  src/main/java/com/sopkathon/server/service/ResultService.java
  src/main/java/com/sopkathon/server/service/UserService.java
Labels: feat, 성은🩳
